/*
 * The my-eyes icon set.
 *
 * Generated by bin/build-icons.php from resources/icons — do not edit by
 * hand. Add an icon by dropping a 24x24 SVG in there and running the script.
 */

export type BundledIconName =
    | 'activity'
    | 'alert-circle'
    | 'alert-triangle'
    | 'archive'
    | 'arrow-down'
    | 'arrow-left'
    | 'arrow-right'
    | 'arrow-up'
    | 'at-sign'
    | 'banknote'
    | 'bar-chart'
    | 'barcode'
    | 'bell-off'
    | 'bell'
    | 'bookmark'
    | 'briefcase'
    | 'building'
    | 'calculator'
    | 'calendar-check'
    | 'calendar'
    | 'check-circle'
    | 'check'
    | 'chevron-down'
    | 'chevron-left'
    | 'chevron-right'
    | 'chevron-up'
    | 'circle-x'
    | 'clipboard'
    | 'clock-history'
    | 'clock'
    | 'cloud'
    | 'collapse'
    | 'columns'
    | 'contact'
    | 'copy'
    | 'credit-card'
    | 'database'
    | 'download'
    | 'expand'
    | 'external-link'
    | 'eye-off'
    | 'eye'
    | 'file-check'
    | 'file-plus'
    | 'file-question'
    | 'file-text'
    | 'file-x'
    | 'file'
    | 'filter'
    | 'flag'
    | 'folder-open'
    | 'folder-plus'
    | 'gauge'
    | 'grid'
    | 'headset'
    | 'help-circle'
    | 'home'
    | 'hourglass'
    | 'id-card'
    | 'info'
    | 'invoice'
    | 'key'
    | 'layout-dashboard'
    | 'line-chart'
    | 'link'
    | 'list'
    | 'lock'
    | 'log-in'
    | 'log-out'
    | 'mail'
    | 'maximize'
    | 'menu'
    | 'message-square'
    | 'minimize'
    | 'minus'
    | 'monitor'
    | 'moon'
    | 'more-horizontal'
    | 'more-vertical'
    | 'package'
    | 'panel-left'
    | 'paperclip'
    | 'pencil'
    | 'percent'
    | 'phone'
    | 'pie-chart'
    | 'plus'
    | 'power'
    | 'printer'
    | 'receipt'
    | 'redo'
    | 'refresh'
    | 'save'
    | 'search'
    | 'send'
    | 'server-crash'
    | 'server'
    | 'settings'
    | 'share'
    | 'shield-off'
    | 'shield'
    | 'shopping-cart'
    | 'sort-asc'
    | 'sort-desc'
    | 'star'
    | 'sun'
    | 'table'
    | 'tag'
    | 'target'
    | 'terminal'
    | 'thumbs-down'
    | 'thumbs-up'
    | 'trash'
    | 'trending-down'
    | 'trending-up'
    | 'truck'
    | 'undo'
    | 'unlock'
    | 'upload-cloud'
    | 'upload'
    | 'user-check'
    | 'user-group'
    | 'user-plus'
    | 'user-x'
    | 'user'
    | 'users'
    | 'wallet'
    | 'x'

export const bundledIcons: Record<BundledIconName, string> = {
    'activity': '<path d="M22 12h-4l-3 9L9 3l-3 9H2"/>',
    'alert-circle': '<circle cx="12" cy="12" r="9"/><path d="M12 8v4"/><path d="M12 16h.01"/>',
    'alert-triangle': '<path d="M10.3 3.9 1.8 18a2 2 0 0 0 1.7 3h17a2 2 0 0 0 1.7-3L13.7 3.9a2 2 0 0 0-3.4 0z"/><path d="M12 9v4"/><path d="M12 17h.01"/>',
    'archive': '<rect width="20" height="5" x="2" y="3" rx="1"/><path d="M4 8v11a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8"/><path d="M10 12h4"/>',
    'arrow-down': '<path d="M12 5v14"/><path d="m19 12-7 7-7-7"/>',
    'arrow-left': '<path d="M19 12H5"/><path d="m12 19-7-7 7-7"/>',
    'arrow-right': '<path d="M5 12h14"/><path d="m12 5 7 7-7 7"/>',
    'arrow-up': '<path d="M12 19V5"/><path d="m5 12 7-7 7 7"/>',
    'at-sign': '<circle cx="12" cy="12" r="4"/><path d="M16 8v5a2.5 2.5 0 0 0 5 0v-1a9 9 0 1 0-4 7.5"/>',
    'banknote': '<rect width="20" height="12" x="2" y="6" rx="2"/><circle cx="12" cy="12" r="2.5"/><path d="M6 12h.01M18 12h.01"/>',
    'bar-chart': '<path d="M3 20h18"/><path d="M6.5 20V10"/><path d="M12 20V4"/><path d="M17.5 20V14"/>',
    'barcode': '<path d="M3.5 5v14M6 5v14M10.5 5v14"/><path d="M14 5v14M16.5 5v14M20.5 5v14"/>',
    'bell-off': '<path d="M7.5 4.5A6 6 0 0 1 18 8c0 6.5 3 8.5 3 8.5h-4.5"/><path d="M16.5 16.5H3s3-2 3-8.5"/><path d="M10.5 20.5a2.5 2.5 0 0 0 3 0"/><path d="m2 2 20 20"/>',
    'bell': '<path d="M18 8A6 6 0 0 0 6 8c0 6.5-3 8.5-3 8.5h18s-3-2-3-8.5"/><path d="M10.5 20.5a2.5 2.5 0 0 0 3 0"/>',
    'bookmark': '<path d="m19 21-7-4-7 4V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2z"/>',
    'briefcase': '<rect width="20" height="14" x="2" y="7" rx="2"/><path d="M8 7V5a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"/>',
    'building': '<path d="M5 21V5a2 2 0 0 1 2-2h5a2 2 0 0 1 2 2v16"/><path d="M14 21v-9h3a2 2 0 0 1 2 2v7"/><path d="M3 21h18"/><path d="M7.5 9h4M7.5 15h4"/>',
    'calculator': '<rect width="16" height="20" x="4" y="2" rx="2"/><path d="M8 7h8"/><path d="M9 13h.01M15 13h.01"/><path d="M9 17.5h.01M15 17.5h.01"/>',
    'calendar-check': '<rect width="18" height="18" x="3" y="4" rx="2"/><path d="M8 2v4"/><path d="M16 2v4"/><path d="M3 10h18"/><path d="m8.5 15.5 2.5 2.5 4.5-5"/>',
    'calendar': '<rect width="18" height="18" x="3" y="4" rx="2"/><path d="M8 2v4"/><path d="M16 2v4"/><path d="M3 10h18"/>',
    'check-circle': '<circle cx="12" cy="12" r="9"/><path d="m8.5 12.5 2.5 2.5 4.5-5"/>',
    'check': '<path d="M20 6 9 17l-5-5"/>',
    'chevron-down': '<path d="m6 9 6 6 6-6"/>',
    'chevron-left': '<path d="m15 18-6-6 6-6"/>',
    'chevron-right': '<path d="m9 18 6-6-6-6"/>',
    'chevron-up': '<path d="m18 15-6-6-6 6"/>',
    'circle-x': '<circle cx="12" cy="12" r="9"/><path d="m15.5 8.5-7 7"/><path d="m8.5 8.5 7 7"/>',
    'clipboard': '<rect width="8" height="4" x="8" y="2" rx="1"/><path d="M16 4h2a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h2"/>',
    'clock-history': '<path d="M3 12a9 9 0 1 0 9-9 9.5 9.5 0 0 0-6.5 3L3 8"/><path d="M3 3v5h5"/><path d="M12 7v5l3 2"/>',
    'clock': '<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',
    'cloud': '<path d="M17 18.5H9a6.5 6.5 0 1 1 6-9h2a4.5 4.5 0 1 1 0 9z"/>',
    'collapse': '<path d="M20 10h-6V4"/><path d="m21 3-7 7"/><path d="M4 14h6v6"/><path d="m3 21 7-7"/>',
    'columns': '<rect width="18" height="18" x="3" y="3" rx="2"/><path d="M9 3v18"/><path d="M15 3v18"/>',
    'contact': '<rect width="18" height="18" x="3" y="3" rx="2"/><circle cx="12" cy="9.5" r="2.5"/><path d="M16.5 17.5v-1A2.5 2.5 0 0 0 14 14h-4a2.5 2.5 0 0 0-2.5 2.5v1"/>',
    'copy': '<rect width="14" height="14" x="8" y="8" rx="2"/><path d="M4 16a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2"/>',
    'credit-card': '<rect width="20" height="14" x="2" y="5" rx="2"/><path d="M2 10h20"/><path d="M6 15h4"/>',
    'database': '<ellipse cx="12" cy="5.5" rx="9" ry="2.5"/><path d="M21 5.5v13a9 2.5 0 0 1-18 0v-13"/><path d="M3 12a9 2.5 0 0 0 18 0"/>',
    'download': '<path d="M12 3v10"/><path d="m7.5 8.5 4.5 4.5 4.5-4.5"/><path d="M20 16v3a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2v-3"/>',
    'expand': '<path d="M15 3h6v6"/><path d="m21 3-7 7"/><path d="M9 21H3v-6"/><path d="m3 21 7-7"/>',
    'external-link': '<path d="M15 3h6v6"/><path d="M10 14 21 3"/><path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6"/>',
    'eye-off': '<path d="M10.7 5.1A11 11 0 0 1 12 5c5 0 9 3.5 9.9 6.6a1 1 0 0 1 0 .7 11.6 11.6 0 0 1-2.2 3.4"/><path d="M6.6 6.6A11.5 11.5 0 0 0 2.1 11.6a1 1 0 0 0 0 .7C3 15.5 7 19 12 19a11 11 0 0 0 5.4-1.4"/><path d="m2 2 20 20"/><path d="M9.9 9.9a3 3 0 0 0 4.2 4.2"/>',
    'eye': '<path d="M2.06 12.35a1 1 0 0 1 0-.7 10.75 10.75 0 0 1 19.88 0 1 1 0 0 1 0 .7 10.75 10.75 0 0 1-19.88 0z"/><circle cx="12" cy="12" r="3"/>',
    'file-check': '<path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><path d="M14 2v6h6"/><path d="m8.5 15 2.5 2.5 4.5-5"/>',
    'file-plus': '<path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><path d="M14 2v6h6"/><path d="M12 12v6"/><path d="M9 15h6"/>',
    'file-question': '<path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><path d="M14 2v6h6"/><path d="M10 13a2 2 0 1 1 3 1.7c-.6.4-1 .8-1 1.6"/><path d="M12 19h.01"/>',
    'file-text': '<path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><path d="M14 2v6h6"/><path d="M8 13h8"/><path d="M8 17h5"/>',
    'file-x': '<path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><path d="M14 2v6h6"/><path d="m15 12-6 6"/><path d="m9 12 6 6"/>',
    'file': '<path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><path d="M14 2v6h6"/>',
    'filter': '<path d="M2 3h20l-7.5 8.5v7l-5 2v-9z"/>',
    'flag': '<path d="M4.5 14.5s1.5-1 4-1 5.5 2 8 2 4-1 4-1V3.5s-1.5 1-4 1-5.5-2-8-2-4 1-4 1z"/><path d="M4.5 21v-6.5"/>',
    'folder-open': '<path d="M2 13.5V6a2 2 0 0 1 2-2h4l2.5 3H20a2 2 0 0 1 2 2v2"/><path d="M2 13.5 5 11h17l-3 9H4a2 2 0 0 1-2-2z"/>',
    'folder-plus': '<path d="M22 18a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h4l2.5 3H20a2 2 0 0 1 2 2z"/><path d="M12 10.5v6"/><path d="M9 13.5h6"/>',
    'gauge': '<path d="M3 16.5a9 9 0 0 1 18 0"/><path d="m12 16.5 4.5-4.5"/><circle cx="12" cy="16.5" r="1"/>',
    'grid': '<rect width="7" height="7" x="3" y="3" rx="1"/><rect width="7" height="7" x="14" y="3" rx="1"/><rect width="7" height="7" x="3" y="14" rx="1"/><rect width="7" height="7" x="14" y="14" rx="1"/>',
    'headset': '<path d="M4.5 13v-1a7.5 7.5 0 0 1 15 0v1"/><rect width="5" height="6" x="2" y="13" rx="1"/><rect width="5" height="6" x="17" y="13" rx="1"/><path d="M19.5 19v1a2 2 0 0 1-2 2H14"/>',
    'help-circle': '<circle cx="12" cy="12" r="9"/><path d="M9.5 9.5a2.75 2.75 0 0 1 5 1.25c0 1.75-2.5 2.25-2.5 2.25"/><path d="M12 16.5h.01"/>',
    'home': '<path d="m3 10 9-7 9 7v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/><path d="M9 21v-8h6v8"/>',
    'hourglass': '<path d="M5 2h14"/><path d="M5 22h14"/><path d="M6.5 2v5.5l5.5 4.5 5.5-4.5V2"/><path d="M6.5 22v-5.5l5.5-4.5 5.5 4.5V22"/>',
    'id-card': '<rect width="20" height="14" x="2" y="5" rx="2"/><circle cx="8" cy="12" r="2.5"/><path d="M14 10h4.5"/><path d="M14 14h4.5"/>',
    'info': '<circle cx="12" cy="12" r="9"/><path d="M12 16v-4"/><path d="M12 8h.01"/>',
    'invoice': '<path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><path d="M14 2v6h6"/><path d="M8 12h8"/><circle cx="12" cy="17" r="2.5"/>',
    'key': '<path d="m21 2-9.5 9.5"/><path d="m15.5 7.5 3 3L22 7l-3-3"/><circle cx="7.5" cy="15.5" r="5.5"/>',
    'layout-dashboard': '<rect width="7" height="9" x="3" y="3" rx="1"/><rect width="7" height="5" x="14" y="3" rx="1"/><rect width="7" height="9" x="14" y="12" rx="1"/><rect width="7" height="5" x="3" y="16" rx="1"/>',
    'line-chart': '<path d="M4 4v16h16"/><path d="m7.5 15.5 3.5-4 3 2.5 4.5-6"/>',
    'link': '<path d="M10 13a5 5 0 0 0 7.5.5l3-3a5 5 0 0 0-7-7l-1.75 1.75"/><path d="M14 11a5 5 0 0 0-7.5-.5l-3 3a5 5 0 0 0 7 7l1.75-1.75"/>',
    'list': '<path d="M4 6h.01M4 12h.01M4 18h.01"/><path d="M9 6h11"/><path d="M9 12h11"/><path d="M9 18h11"/>',
    'lock': '<rect width="18" height="11" x="3" y="11" rx="2"/><path d="M7 11V7a5 5 0 0 1 10 0v4"/>',
    'log-in': '<path d="M15 3h4a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2h-4"/><path d="m10 17 5-5-5-5"/><path d="M15 12H3"/>',
    'log-out': '<path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"/><path d="m16 17 5-5-5-5"/><path d="M21 12H9"/>',
    'mail': '<rect width="20" height="16" x="2" y="4" rx="2"/><path d="m2 7 8.9 5.5a2 2 0 0 0 2.2 0L22 7"/>',
    'maximize': '<path d="M9 3H5a2 2 0 0 0-2 2v4"/><path d="M21 9V5a2 2 0 0 0-2-2h-4"/><path d="M3 15v4a2 2 0 0 0 2 2h4"/><path d="M15 21h4a2 2 0 0 0 2-2v-4"/>',
    'menu': '<path d="M4 6h16"/><path d="M4 12h16"/><path d="M4 18h16"/>',
    'message-square': '<path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"/>',
    'minimize': '<path d="M8 2v4a2 2 0 0 1-2 2H2"/><path d="M22 8h-4a2 2 0 0 1-2-2V2"/><path d="M2 16h4a2 2 0 0 1 2 2v4"/><path d="M16 22v-4a2 2 0 0 1 2-2h4"/>',
    'minus': '<path d="M5 12h14"/>',
    'monitor': '<rect width="20" height="14" x="2" y="3" rx="2"/><path d="M8 21h8"/><path d="M12 17v4"/>',
    'moon': '<path d="M12 3a6 6 0 0 0 9 9 9 9 0 1 1-9-9z"/>',
    'more-horizontal': '<circle cx="5" cy="12" r="1"/><circle cx="12" cy="12" r="1"/><circle cx="19" cy="12" r="1"/>',
    'more-vertical': '<circle cx="12" cy="5" r="1"/><circle cx="12" cy="12" r="1"/><circle cx="12" cy="19" r="1"/>',
    'package': '<path d="M12 3 21 7v10l-9 4-9-4V7z"/><path d="m3 7 9 4 9-4"/><path d="M12 11v10"/><path d="m7.5 5 9 4"/>',
    'panel-left': '<rect width="18" height="18" x="3" y="3" rx="2"/><path d="M9 3v18"/>',
    'paperclip': '<path d="m21 10-9.5 9.5a4.9 4.9 0 0 1-7-7l8.5-8.5a2.4 2.4 0 0 1 3.5 3.5l-6.5 6.5"/>',
    'pencil': '<path d="M3.5 20.5 5.5 14.5 16.5 3.5a3 3 0 0 1 4 4l-11 11Z"/><path d="m14.5 5.5 4 4"/>',
    'percent': '<path d="M19 5 5 19"/><circle cx="6.5" cy="6.5" r="2.5"/><circle cx="17.5" cy="17.5" r="2.5"/>',
    'phone': '<path d="M22 16.5v3a2 2 0 0 1-2 2A18 18 0 0 1 2.5 4a2 2 0 0 1 2-2h3a2 2 0 0 1 2 1.5 12 12 0 0 0 .5 2.5 2 2 0 0 1-.5 2L8 9.5a16 16 0 0 0 6.5 6.5l1.5-1a2 2 0 0 1 2-.5 12 12 0 0 0 2.5.5A2 2 0 0 1 22 16.5z"/>',
    'pie-chart': '<circle cx="12" cy="12" r="9"/><path d="M12 3v9h9"/>',
    'plus': '<path d="M12 5v14"/><path d="M5 12h14"/>',
    'power': '<path d="M12 2v10"/><path d="M6.6 4.8a9 9 0 1 0 10.8 0"/>',
    'printer': '<path d="M6 9V4a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v5"/><path d="M6 18H4a2 2 0 0 1-2-2v-5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2h-2"/><rect width="12" height="8" x="6" y="14" rx="2"/>',
    'receipt': '<path d="M5 21.5 8.5 19.5 12 21.5 15.5 19.5 19 21.5V4a2 2 0 0 0-2-2H7a2 2 0 0 0-2 2z"/><path d="M8.5 7.5h7"/><path d="M8.5 12h7"/><path d="M8.5 16.5h3.5"/>',
    'redo': '<path d="m15 14 5-5-5-5"/><path d="M20 9H9a5 5 0 0 0 0 10h4"/>',
    'refresh': '<path d="M3 12a9 9 0 0 1 9-9 9.5 9.5 0 0 1 6.5 2.5L21 8"/><path d="M21 3v5h-5"/><path d="M21 12a9 9 0 0 1-9 9 9.5 9.5 0 0 1-6.5-2.5L3 16"/><path d="M3 21v-5h5"/>',
    'save': '<path d="M16 3H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V8z"/><path d="M8 3v5h6V3"/><path d="M17 21v-6H7v6"/>',
    'search': '<circle cx="11" cy="11" r="7"/><path d="m20 20-3.5-3.5"/>',
    'send': '<path d="m21.5 2.5-7 19-4-8.5-8.5-4z"/><path d="M18.5 5.5 10.5 13"/>',
    'server-crash': '<path d="M6 10H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v3a2 2 0 0 1-2 2h-2"/><path d="M6 14H4a2 2 0 0 0-2 2v3a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2v-3a2 2 0 0 0-2-2h-2"/><path d="M6 6h.01"/><path d="M6 18h.01"/><path d="m13 6-4 6h6l-4 6"/>',
    'server': '<rect width="20" height="7" x="2" y="3" rx="2"/><rect width="20" height="7" x="2" y="14" rx="2"/><path d="M6 6.5h.01"/><path d="M6 17.5h.01"/>',
    'settings': '<path d="M12.2 2h-.4a2 2 0 0 0-2 2v.2a2 2 0 0 1-1 1.7l-.4.2a2 2 0 0 1-2 0l-.2-.1a2 2 0 0 0-2.7.7l-.2.4a2 2 0 0 0 .7 2.7l.2.1a2 2 0 0 1 1 1.7v.5a2 2 0 0 1-1 1.7l-.2.1a2 2 0 0 0-.7 2.7l.2.4a2 2 0 0 0 2.7.7l.2-.1a2 2 0 0 1 2 0l.4.2a2 2 0 0 1 1 1.7v.2a2 2 0 0 0 2 2h.4a2 2 0 0 0 2-2v-.2a2 2 0 0 1 1-1.7l.4-.2a2 2 0 0 1 2 0l.2.1a2 2 0 0 0 2.7-.7l.2-.4a2 2 0 0 0-.7-2.7l-.2-.1a2 2 0 0 1-1-1.7v-.5a2 2 0 0 1 1-1.7l.2-.1a2 2 0 0 0 .7-2.7l-.2-.4a2 2 0 0 0-2.7-.7l-.2.1a2 2 0 0 1-2 0l-.4-.2a2 2 0 0 1-1-1.7V4a2 2 0 0 0-2-2z"/><circle cx="12" cy="12" r="3"/>',
    'share': '<circle cx="6" cy="12" r="3"/><circle cx="18" cy="5.5" r="3"/><circle cx="18" cy="18.5" r="3"/><path d="m9.5 10 5-2.5M9.5 14l5 2.5"/>',
    'shield-off': '<path d="M19.7 14A9 9 0 0 0 20 11V5l-8-3-3.5 1.3"/><path d="M4.7 4.7 4 5v6c0 5 3.4 8.4 7.3 9.9a1 1 0 0 0 .7 0 12 12 0 0 0 4-2.4"/><path d="m2 2 20 20"/>',
    'shield': '<path d="M20 11V5l-8-3-8 3v6c0 5 3.4 8.4 7.3 9.9a1 1 0 0 0 1.4 0c3.9-1.5 7.3-4.9 7.3-9.9z"/>',
    'shopping-cart': '<path d="M5.5 7.5H21l-2.5 7.5H7.5L4.5 4H2.5"/><path d="M10 19h.01M17 19h.01"/>',
    'sort-asc': '<path d="M6 20V4M3 7.5l3-3.5 3 3.5"/><path d="M12 6h3"/><path d="M12 12h6"/><path d="M12 18h9"/>',
    'sort-desc': '<path d="M6 4v16M3 16.5l3 3.5 3-3.5"/><path d="M12 6h9"/><path d="M12 12h6"/><path d="M12 18h3"/>',
    'star': '<path d="M12 3.5 14 10h7l-5.5 4 2 6.5-5.5-4-5.5 4 2-6.5L3 10h7z"/>',
    'sun': '<circle cx="12" cy="12" r="4"/><path d="M12 2v2"/><path d="M12 20v2"/><path d="m4.9 4.9 1.4 1.4"/><path d="m17.7 17.7 1.4 1.4"/><path d="M2 12h2"/><path d="M20 12h2"/><path d="m6.3 17.7-1.4 1.4"/><path d="m19.1 4.9-1.4 1.4"/>',
    'table': '<rect width="18" height="18" x="3" y="3" rx="2"/><path d="M3 9h18"/><path d="M12 9v12"/>',
    'tag': '<path d="M11.5 2.5H4.5a2 2 0 0 0-2 2v7l10 10 9-9z"/><path d="M7 7h.01"/>',
    'target': '<circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="5"/><circle cx="12" cy="12" r="1"/>',
    'terminal': '<rect width="18" height="18" x="3" y="3" rx="2"/><path d="m7.5 9 3 3-3 3"/><path d="M13 15h3.5"/>',
    'thumbs-down': '<path d="M9.5 14.5v3.5a3.5 3.5 0 0 0 3.5 3.5l3.5-8v-11H6a2 2 0 0 0-2 1.5l-1 8a2 2 0 0 0 1.5 2.5z"/><path d="M16.5 2.5h3a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2h-3"/>',
    'thumbs-up': '<path d="M14.5 9.5V6A3.5 3.5 0 0 0 11 2.5L7.5 10.5v11h10.5a2 2 0 0 0 2-1.5l1-8a2 2 0 0 0-1.5-2.5z"/><path d="M7.5 21.5H4.5a2 2 0 0 1-2-2v-5a2 2 0 0 1 2-2h3"/>',
    'trash': '<path d="M3 6h18"/><path d="M19 6v13a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6"/><path d="M8 6V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"/>',
    'trending-down': '<path d="m22 17-8.5-8.5-5 5L2 7"/><path d="M16 17h6v-6"/>',
    'trending-up': '<path d="m22 7-8.5 8.5-5-5L2 17"/><path d="M16 7h6v6"/>',
    'truck': '<path d="M13.5 18V6a2 2 0 0 0-2-2h-7a2 2 0 0 0-2 2v12h2.5m4 0h6.5"/><path d="M13.5 8H18l3.5 4.5V16a2 2 0 0 1-2 2"/><circle cx="7" cy="18" r="2"/><circle cx="17.5" cy="18" r="2"/>',
    'undo': '<path d="M9 14 4 9l5-5"/><path d="M4 9h11a5 5 0 0 1 0 10h-4"/>',
    'unlock': '<rect width="18" height="11" x="3" y="11" rx="2"/><path d="M7 11V7a5 5 0 0 1 8.5-3.5"/>',
    'upload-cloud': '<path d="M12 13v8"/><path d="m8 17 4-4 4 4"/><path d="M20.9 18.4A5 5 0 0 0 18 9h-1.3A8 8 0 1 0 4 16.2"/>',
    'upload': '<path d="M12 3v10"/><path d="m7.5 7.5 4.5-4.5 4.5 4.5"/><path d="M20 16v3a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2v-3"/>',
    'user-check': '<path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="m16 11 2 2 4-4"/>',
    'user-group': '<path d="M20.5 20v-1a3.5 3.5 0 0 0-3.5-3.5H7A3.5 3.5 0 0 0 3.5 19v1"/><circle cx="12" cy="8" r="3"/><circle cx="5" cy="10.5" r="2"/><circle cx="19" cy="10.5" r="2"/>',
    'user-plus': '<path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M19 8v6"/><path d="M22 11h-6"/>',
    'user-x': '<path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="m16.5 8.5 5 5"/><path d="m21.5 8.5-5 5"/>',
    'user': '<path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2"/><circle cx="12" cy="7" r="4"/>',
    'users': '<path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.9"/><path d="M16 3.1a4 4 0 0 1 0 7.8"/>',
    'wallet': '<rect width="20" height="15" x="2" y="4.5" rx="2"/><path d="M22 9.5h-4.5a2.5 2.5 0 0 0 0 5H22"/>',
    'x': '<path d="M18 6 6 18"/><path d="m6 6 12 12"/>',
}
